### ISSUE TITLE
Please provide a License file

### ISSUE THREAD

**Issue by bachp** [konikvranik/pyCEC#37]
There should be a LICENSE or COPYRIGHT file with the repository stating what license the project is under.

For example if the project is MIT licensed include a file like for example [netdisco](https://github.com/home-assistant/netdisco/blob/master/LICENSE) does.

The LICNESE file should also be included in the Tarball uploaded to PyPi.
This makes it easier for packagers to package your library.

**Comment by konikvranik** [comment]
done

**Comment by bachp** [comment]
Thank you
