### ISSUE TITLE
Install on LibreElec

### ISSUE THREAD

**Issue by addebc** [konikvranik/pyCEC#45]
Looking for a way to install this on libreelec.

Is there a way to make this supported as a Kodi(xbmc) addon. Since LibreElec has tightened down the raspberry on the os and wont install anything...

**Comment by konikvranik** [comment]
What is your intent? What do you want Kodi to do?
Kodi has it's own CEC support.

**Comment by addebc** [comment]
Intent is to controll the HDMI remotely via Home Assistant. 
But an easy solution I guess is to use a second raspberry for that then.

**Comment by konikvranik** [comment]
I still do not understand. What role plays XBMC here? You want to controll XBMC via Home Assistant? There is plugin for it. You can add Kodi as media player to Home Assistant.

**Comment by k0rtina** [comment]
I am interested too.

EG:
Home Assistant running on a headless server (192.168.1.10)
KODI running on Chromebox (LibreElec), with Pulse-Eight CEC adapter (192.168.1.20)
KODI attached to a HDMI amp, and a simple LCD screen (no smart features).

The aim is to get Home Assistant to tell KODI to use the CEC adapter to turn on the Amp and TV, and turn the TV to HDMI2.

https://home-assistant.io/components/hdmi_cec/
hdmi_cec:
  host: 192.168.1.20

**Comment by konikvranik** [comment]
@k0rtina You wish to command Kodi to send CEC commands? So right place is Kodi plugin to realize this. Or you can run pycec server on libreelec machine and configure ha pycec plugin to connect this server.

**Comment by addelovein** [comment]
No that was the problem. Never could install Pycec server on libreelec.
