### ISSUE TITLE
autostart pycec

### ISSUE THREAD

**Issue by Yannik25** [konikvranik/pyCEC#47]
Hallo, 
I run `pip3 install pycec` to install this and by entering this command: `python3 –m pycec` 
it will start. 
It seemed to me to be installed in this directory: /home/pi/.local/bin/pycec.
By also entering `/home/pi/.local/bin/pycec` pycec will start

but when i want to add it to a service 

```
[Unit]
Description=pycec

[Service]
ExecStart=/home/pi/.local/bin/pycec

[Install]
WantedBy=multi-user.target
```

i will get following error:
`ImportError: No module named 'pycec'`

I think it is a issue with the path, but how to fix it?
I am using Raspbian stretch

Thanks for any help

**Comment by konikvranik** [comment]
It's more about python environment setup. Try to google running python scripts as a systemd service.
