### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by balloob** [konikvranik/pyCEC#53]
Could we get a new release published that includes merged PR #52 ? Because `typing` is now always installed, users need to run `pip uninstall typing` to fix their environments after installing pyCEC. Thanks!

**Comment by balloob** [comment]
@konikvranik, would you have time to publish a new release? Thanks!

**Comment by konikvranik** [comment]
I'm not owner. You have to ask @jbarrancos.

**Comment by balloob** [comment]
@jbarrancos would you have time for this?

**Comment by jbarrancos** [comment]
I’ll be back in NL monday and make a build



Op 1 aug. 2020 om 15:39 heeft Paulus Schoutsen <notifications@github.com> het volgende geschreven:

﻿

@jbarrancos<https://github.com/jbarrancos> would you have time for this?

**Comment by balloob** [comment]
@jbarrancos did you make it back to Holland? :)

**Comment by jbarrancos** [comment]
pyRainbirds new version is published 2 weeks ago. HA updates can be done by anyone. Did not see any pull reqs

Op 26 aug. 2020 om 09:58 heeft Paulus Schoutsen <notifications@github.com> het volgende geschreven:

﻿

@jbarrancos<https://github.com/jbarrancos> did you make it back to Holland? :)

**Comment by balloob** [comment]
My bad. I missed that. Will update Home Assistant.

**Comment by balloob** [comment]
@jbarrancos this is an issue about a new pyCEC release, not pyrainbirds

**Comment by jbarrancos** [comment]
I only manage the pyRainbird package

**Comment by balloob** [comment]
Oh, @konikvranik pointed at you for a new release. Little confused now 👀

**Comment by jbarrancos** [comment]
I think he is confused with a different PR ;) and so am I ;) @konikvranik  this seems to be your repo here and on PyPi https://pypi.org/project/pyCEC/

**Comment by konikvranik** [comment]
@jbarrancos, @balloob My mistake. Sorry for that. I'll check pyCEC ASAP.

**Comment by TheDK** [comment]
As HDMI CEC will not be usable with 0.115 can you indicate if there will be an update soon (so to wait with installing 0.115) or if it might be longer if this will be fixed if at all? Thanks!

**Comment by christovic** [comment]
Love to know this too, this is the only thing stopping me from upgrading, or whether I should start working on another solution! :+1:

**Comment by TheDK** [comment]
@konikvranik Just wanted to make sure you're getting this - a quick indication if there's a future for this or if we should be looking for something else would be much appreciated.

**Comment by newAM** [comment]
@konikvranik I know people get busy, if you need any help with maintenance (even if it is just someone to do this release) I can help out.

Additional maintainers can be added on pypi here: https://pypi.org/manage/project/pyCEC/collaboration/
And on github here: https://github.com/konikvranik/pyCEC/settings/access

My username is `newAM` on both.

**Comment by konikvranik** [comment]
Hi @newAM, thank you for you offer. I added you to pypi repo as maintainer, so if you can release new version, I'll be happy.

**Comment by newAM** [comment]
Fantastic!  I made a release (0.4.14).  I do not have repo access so the PR with the changes (one line) is here: #56

**Comment by newAM** [comment]
Home-assistant pull-request open here: https://github.com/home-assistant/core/pull/40671
