### ISSUE TITLE
v0.4.14 pypi package not in sync with GitHub

### ISSUE THREAD

**Issue by rajlaud** [konikvranik/pyCEC#62]
When I installed latest version using pip, the merged changes from https://github.com/konikvranik/pyCEC/pull/54 don't appear. However, they are incorporated in the github release tag. Can you upload a new release?

**Comment by newAM** [comment]
I'll make a 0.5.0 release with those changes this weekend.

The tagged commit for v0.4.14 is 62706679de248557e00666fd547fb6d462d9039a, which does not include those changes.  It got merged after the changes from #54 which it why it appears in the commit range.

**Comment by rajlaud** [comment]
Thank you for the clarification

**Comment by newAM** [comment]
Changes are captured in the 0.5.0 release.  Will make the changes upstream to home assistant as well.
